include ~/.cache/wal/colors-kitty.conf

allow_remote_control yes
listen_on unix:/tmp/kitty
shell_integration no-sudo


# Minimal Tab bar styling 
tab_bar_edge                bottom
tab_bar_style               powerline
tab_powerline_style         slanted
tab_title_template          {title}{' :{}:'.format(num_windows) if num_windows > 1 else ''}

# Fonts
font_family      JetBrainsMono Nerd Font
bold_font        JetBrainsMono Nerd Font Bold
italic_font      JetBrainsMono Nerd Font Italic
bold_italic_font JetBrainsMono Nerd Font Bold Italic
font_size 12.0

enable_audio_bell no
window_padding_width 10
confirm_os_window_close 0






dynamic_background_opacity no

#linux_display_server x11

# OS Window titlebar colors
#wayland_titlebar_color  #1E1E2E
#macos_titlebar_color    #1E1E2E