#!/usr/bin/env bash

# Open Terminal (Ctrl + Return)
ctrl - return : open -n /Applications/kitty.app

# Open Browser (Ctrl + b)
ctrl - b : open -n /Applications/Firefox.app

shift + ctrl -w : /bin/zsh -i -c /Users/thm/scripts/wallpapermenu.sh


shift + cmd - 4 : /Applications/flameshot.app/Contents/MacOS/flameshot gui


shift + ctrl - r : \
    #aerospace --restart-service; \
    skhd --restart-service; \
    osascript -e 'display notification "aerospace & skhd reloaded" with title "System"'