export const theme = {
  name: "Pywal",
  kind: "dark",
  main: "{background}",
  mainAlt: "{color0}",
  minor: "{color8}",
  red: "{color1}",
  green: "{color2}",
  yellow: "{color3}",
  orange: "{color9}",
  blue: "{color4}",
  magenta: "{color5}",
  cyan: "{color6}",
  black: "{color0}",
  white: "{color7}",
  foreground: "{foreground}",
  transparentDark: "rgba(0, 0, 0, 0.15)",
  defaultFont: "JetBrains Mono, Monaco, Menlo, monospace",
  barHeight: "34px",
  compactBarHeight: "28px",
  barRadius: "3px",
  barBorder: "0px solid transparent",
  barInnerMargin: "3px",
  itemRadius: "2px",
  itemInnerMargin: "3px 7px",
  itemOuterMargin: "0 0 0 5px",
  hoverRing: "0 0 0 2px rgba(152, 168, 198, 0.5)",
  focusRing: "0 0 0 2px rgba(152, 168, 198, 0.5)",
  lightShadow: "0 5px 10px rgba(0, 0, 0, 0.24)",
  transitionEasing: "cubic-bezier(0.4, 0, 0.2, 1)",
  clickEffect: "rgba(0, 0, 0, 0.15)",
};