#!/bin/bash

# Generated by pywal - Do not edit manually

export background='0x{background.alpha_hex}{background.strip}'
export foreground='0x{foreground.alpha_hex}{foreground.strip}'
export cursor='{cursor}'
export alpha='{alpha}'

# Colors
export color0='0x{color0.alpha_hex}{color0.strip}'
export color1='0x{color1.alpha_hex}{color1.strip}'
export color2='0x{color2.alpha_hex}{color2.strip}'
export color3='0x{color3.alpha_hex}{color3.strip}'
export color4='0x{color4.alpha_hex}{color4.strip}'
export color5='0x{color5.alpha_hex}{color5.strip}'
export color6='0x{color6.alpha_hex}{color6.strip}'
export color7='0x{color7.alpha_hex}{color7.strip}'
export color8='0x{color8.alpha_hex}{color8.strip}'
export color9='0x{color9.alpha_hex}{color9.strip}'
export color10='0x{color10.alpha_hex}{color10.strip}'
export color11='0x{color11.alpha_hex}{color11.strip}'
export color12='0x{color12.alpha_hex}{color12.strip}'
export color13='0x{color13.alpha_hex}{color13.strip}'
export color14='0x{color14.alpha_hex}{color14.strip}'
export color15='0x{color15.alpha_hex}{color15.strip}'

export WHITE=$color1

export BAR_COLOR=$background   # darkest  → bar fill

export TEXT_COLOR=$foreground

export ITEM_BG_COLOR=$color1   # mid-dark → item background
export ITEM_COLOR=$color1

export ACCENT_COLOR=$color4    # bright   → highlights / icons

# color for items 
export HIGHLIGHT_BORDER_COLOR=$color1
export DEFAULT_BORDER_COLOR=$BAR_COLOR
